openapi: 3.0.3
info:
  title: Swagger Showbiz Booking Event - OpenAPI 3.0
  description: |-
    This is a sample Showbiz based on the OpenAPI 3.0 specification developed by huyhunghang~ and minatdangngu~
  version: 1.0.11
servers:
  - url: http://localhost:4000
tags:
  - name: users
    description: Some APIs related to user
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Login to system
      description: Login to system with username and password
      operationId: login
      requestBody:
        description: Information of user
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: minatt2002@gmail.com
                password:
                  type: string
                  example: Minat123!
        required: true
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successfully!
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYzOWI3NzgzMjgxYTc5NDc5MmJkOWJkIiwidHlwZSI6MCwidmVyaWZ5IjowLCJpYXQiOjE3MTUwNjQwMzYsImV4cCI6MTcxNTA2NDkzNn0.70wMoAxDxeQOVHidoSybeRyzSPsKUhZvhxo9iEnl1nY
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYzOWI3NzgzMjgxYTc5NDc5MmJkOWJkIiwidHlwZSI6MSwidmVyaWZ5IjowLCJpYXQiOjE3MTUwNjQwMzYsImV4cCI6MTcyMzcwNDAzNn0.e5zpNE_dJGnsM9Ur8EJGiHZ9caCMYHW01q-GA3beYUs
        '422':
          description: VALIDATION ERROR!
  /users/register:
    post:
      tags:
        - users
      summary: Register account
      description: Register account with some info like email, password, confirm_password, name, date_of_birth
      operationId: register
      requestBody:
        description: Information of user
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: minatt2002@gmail.com
                password:
                  type: string
                  example: Minat123!
                confirm_password:
                  type: string
                  example: Minat123!
                name: 
                  type: string
                  example: minat
                date_of_birth:
                  type: string 
                  example: 2024-04-28T02:02:41.198Z
        required: true
      responses:
        '200':
          description: Register successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Register successfully!
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYzYzdlZGNjOTA5ZTEzZGNlNTc3OWY1IiwidHlwZSI6MCwidmVyaWZ5IjowLCJpYXQiOjE3MTUyNDA2NjgsImV4cCI6MTcxNTI0MTU2OH0.Kv18GD--BxBiH_3fuPDxTini4iNobPFFONT8Mvt7pY0
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYzYzdlZGNjOTA5ZTEzZGNlNTc3OWY1IiwidHlwZSI6MSwidmVyaWZ5IjowLCJpYXQiOjE3MTUyNDA2NjgsImV4cCI6MTcyMzg4MDY2OH0.3Jhf6QYx3Iv0zJ47fiAOvG4luElrRI5NYOhqN-w7y3A
        '422':
          description: VALIDATION ERROR!
      
        